#!/bin/bash

options=(
	style=square
	width=0.0
	hidpi=on
	active_color=0xCC000000
	inactive_color=0xCC000000
  blacklist="alacritty,System Settings,Digital Color Meter,System Information"
)

borders "${options[@]}"
