live_config_reload = true

[window]
decorations = "None"
opacity = 0.8
padding = { x = 0, y = 0 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 15

[mouse]
hide_when_typing = true

[colors.primary]
foreground = "#FFFFFF"
background = "#000000"

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#000000"
red = "#E62123"
green = "#A6E32B"
yellow = "#FC9520"
blue = "#C48DFF"
magenta = "#FA2572"
cyan = "#67D9F0"
white = "#F2F2F2"

[colors.bright]
black = "#555555"
red = "#FF5455"
green = "#53FF56"
yellow = "#FFFF85"
blue = "#5555FF"
magenta = "#FF54FF"
cyan = "#53FFFF"
white = "#FFFFFF"
