live_config_reload = true

[window]
decorations = "None"
opacity = 0.8
blur = false
padding = { x = 0, y = 0 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
offset = { x = 0, y = 3 }
size = 15

[mouse]
hide_when_typing = true

# [debug]
# persistent_logging = true

[keyboard]
bindings = [
  # Unbind some annoying things
  { key = "T", mods = "Command", action = "None" },
  { key = "W", mods = "Command", action = "None" },
  { key = "N", mods = "Command", action = "None" },
  { key = "M", mods = "Command", action = "None" },
  # Tmux navigation with Cmd + number
  { key = "1", mods = "Command", chars = "\u0001" }, { key = "1", mods = "Command", chars = "1" },
  { key = "2", mods = "Command", chars = "\u0001" }, { key = "2", mods = "Command", chars = "2" },
  { key = "3", mods = "Command", chars = "\u0001" }, { key = "3", mods = "Command", chars = "3" },
  { key = "4", mods = "Command", chars = "\u0001" }, { key = "4", mods = "Command", chars = "4" },
  { key = "5", mods = "Command", chars = "\u0001" }, { key = "5", mods = "Command", chars = "5" },
  { key = "6", mods = "Command", chars = "\u0001" }, { key = "6", mods = "Command", chars = "6" },
  { key = "7", mods = "Command", chars = "\u0001" }, { key = "7", mods = "Command", chars = "7" },
  { key = "8", mods = "Command", chars = "\u0001" }, { key = "8", mods = "Command", chars = "8" },
  { key = "9", mods = "Command", chars = "\u0001" }, { key = "9", mods = "Command", chars = "9" },
]

[colors.primary]
foreground = "#FFFFFF"
background = "#000000"

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#000000"
red = "#E62123"
green = "#A6E32B"
yellow = "#FC9520"
blue = "#C48DFF"
magenta = "#FA2572"
cyan = "#67D9F0"
white = "#F2F2F2"

[colors.bright]
black = "#555555"
red = "#FF5455"
green = "#53FF56"
yellow = "#FFFF85"
blue = "#5555FF"
magenta = "#FF54FF"
cyan = "#53FFFF"
white = "#EEFFFF"
